### ISSUE TITLE
Not working on IE11

### ISSUE THREAD

**Issue by Czelly** [rguliev/conditionize.js#1]
Dear Author!

I am using your conditionize.js on my website. Everything is working fine except on IE11. On IE11 the fields are not hidden and the logic is not working at all.

Do you have any tips for me or how can I get your script working for nearly all browsers? What am I missing?

Thanks,
Chris

**Comment by rguliev** [comment]
Hi Czelly,

I'm glad it can help your website. Could you please provide your not-working code?

**Comment by sachinjhadhav** [comment]
@rguliev Please check the below Error with code pen Link

> Object doesn't support property or method 'includes'

[https://codepen.io/rguliev/pen/geyeOB](url)

Kindly check IE11

**Comment by rguliev** [comment]
Ok. Unfortunately, I don't have a Windows machine available right now. But I'll check it as soon as I will be on Windows machine. It would not take too long.
Thank you for your participation!

**Comment by rguliev** [comment]
Hi, 
I found that the problem is not with `conditionize.js`. The problem is with JS in IE11: it [does not support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes) `includes` function which I used in `data-condition` to check if value is in array.
I changed `data-condition` from `['two','three'].includes(example5)` to `(example5 == 'two') || (example5 == 'three')`. That solved the problem. 
So be careful with condition you use in `data-condition`.
